### ISSUE TITLE
Cannot find entry vendor.xiaomi.hardware.citsensorservice@1.1

### ISSUE THREAD

**Issue by WallyCZ** [markakash/device_xiaomi_cepheus#11]
When device going to doze, following error appears:
> 01-30 19:17:13.428: I/hwservicemanager(570): getTransport: Cannot find entry vendor.xiaomi.hardware.citsensorservice@1.1::ICitSensorService/default in either framework or device 
> 01-30 19:17:13.429: I/QTI PowerHAL(758): Got set_interactive hint on= 0, count= 86
> 01-30 19:17:13.429: E/libsensor-C2SNotifier(752): Query CitSensorService service returned null!
> 01-30 19:17:13.429: E/libsensor-C2SNotifier(752): Sensor: sCitSensorService get failed!

It probable causes display is not dimmed on Ambient display. On original firmware this driver (and display dimming on Ambient display) is working correctly:
> 01-30 20:37:20.802: I/libsensor-C2SNotifier(797): Sensor: notify type: 1, value: 3`

Maybe something is missing in manifest.xml

**Comment by WallyCZ** [comment]
I have managed to add this HAL service, but except disappearing this error message I don't see any other improvement. 
I have added this section to manifext.xml: 
```
<hal format="hidl">
    <name>vendor.xiaomi.hardware.citsensorservice</name>
    <transport>hwbinder</transport>
    <version>1.1</version>
    <interface>
        <name>ICitSensorService</name>
        <instance>default</instance>
    </interface>
    <fqname>@1.1::ICitSensorService/default</fqname>
</hal>
```
and these files:
```
/system/vendor/etc/init/vendor.xiaomi.hardware.citsensorservice@1.1-service.rc
/system/vendor/bin/hw/vendor.xiaomi.hardware.citsensorservice@1.1-service
/system/vendor/lib64/hw/vendor.xiaomi.hardware.citsensorservice@1.1-impl.so
/system/vendor/lib64/vendor.xiaomi.hardware.citsensorservice@1.0.so
/system/vendor/lib64/vendor.xiaomi.hardware.citsensorservice@1.0_vendor.so
/system/vendor/lib64/vendor.xiaomi.hardware.citsensorservice@1.1.so
/system/vendor/lib64/vendor.xiaomi.hardware.citsensorservice@1.1_vendor.so
/system/vendor/lib64/libnanopb.so
/system/vendor/lib64/libssccalapi.so
```

**Comment by markakash** [comment]
Yeah, I don't see adding those sensor stuff fixing anything except for the log spam. Imo its not worth adding useless libs. It calls for it cause we build android.hidl.base@1.0.so and those blobs are dependent on it

**Comment by WallyCZ** [comment]
You are right. This service has probably something with hall sensor, but I am not sure if it is used by something other than MIUI.
