### ISSUE TITLE
Battery draining issue in Mokee ROM

### ISSUE THREAD

**Issue by AaronFeng753** [markakash/device_xiaomi_cepheus#3]
Hi, I'm using your Mokee ROM, nice ROM, already donated 68 CNY, hope you already get the money. And I noticed that my battery is draining very fast when phone is idle. For example, last night, the battery drop 20 percent when I was sleeping. And I don't think this issue was caused by third party apps, because I'm using the same apps as I was using MIUI. Please fix this bug, thank you.

**Comment by markakash** [comment]
Hey, yeah it's known issues for now. I have been working on trying to fix it. Hopefully K get it fixed soon.
